# Generated by Django 5.2.6 on 2025-09-27 17:38

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile Development'), ('data', 'Data Science'), ('ai', 'AI/ML Project'), ('api', 'API Development'), ('general', 'General Programming')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('programming_language', models.CharField(blank=True, max_length=50)),
                ('framework', models.CharField(blank=True, max_length=100)),
                ('repository_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copilot Project',
                'verbose_name_plural': 'Copilot Projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('coding', 'Coding Session'), ('debugging', 'Debugging'), ('review', 'Code Review'), ('planning', 'Project Planning'), ('learning', 'Learning Session')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('goal', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='copilot.copilotproject')),
            ],
            options={
                'verbose_name': 'Copilot Session',
                'verbose_name_plural': 'Copilot Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CopilotInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('question', 'Question'), ('code_generation', 'Code Generation'), ('code_explanation', 'Code Explanation'), ('bug_fix', 'Bug Fix'), ('optimization', 'Code Optimization'), ('suggestion', 'Suggestion')], max_length=20)),
                ('user_input', models.TextField()),
                ('copilot_response', models.TextField()),
                ('code_snippet', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='copilot.copilotsession')),
            ],
            options={
                'verbose_name': 'Copilot Interaction',
                'verbose_name_plural': 'Copilot Interactions',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CopilotCodeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_code', models.TextField(blank=True)),
                ('suggested_code', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('start_line', models.IntegerField(blank=True, null=True)),
                ('end_line', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified')], default='pending', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copilot.copilotsession')),
            ],
            options={
                'verbose_name': 'Copilot Code Suggestion',
                'verbose_name_plural': 'Copilot Code Suggestions',
            },
        ),
        migrations.CreateModel(
            name='CopilotLearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=100)),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('topics_completed', models.JSONField(blank=True, default=list)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('total_practice_time', models.DurationField(default=datetime.timedelta)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Copilot Learning Progress',
                'verbose_name_plural': 'Copilot Learning Progress',
                'unique_together': {('user', 'technology')},
            },
        ),
    ]
