# Generated by Django 5.2.6 on 2025-09-27 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionPersonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('personality_type', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('casual', 'Casual'), ('formal', 'Formal'), ('humorous', 'Humorous'), ('supportive', 'Supportive')], max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='companion_avatars/')),
                ('traits', models.JSONField(blank=True, default=list)),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Companion Personality',
                'verbose_name_plural': 'Companion Personalities',
            },
        ),
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('custom_instructions', models.TextField(blank=True)),
                ('learning_enabled', models.BooleanField(default=True)),
                ('memory_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companion.companionpersonality')),
            ],
            options={
                'verbose_name': 'Companion',
                'verbose_name_plural': 'Companions',
            },
        ),
        migrations.CreateModel(
            name='CompanionConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('mood', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companion.companion')),
            ],
            options={
                'verbose_name': 'Companion Conversation',
                'verbose_name_plural': 'Companion Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('personal', 'Personal Information'), ('preference', 'User Preference'), ('conversation', 'Conversation Context'), ('event', 'Important Event'), ('goal', 'User Goal')], max_length=20)),
                ('content', models.TextField()),
                ('importance', models.IntegerField(default=1)),
                ('last_accessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='companion.companion')),
            ],
            options={
                'verbose_name': 'Companion Memory',
                'verbose_name_plural': 'Companion Memories',
                'ordering': ['-importance', '-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='CompanionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('companion', 'Companion'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('emotion', models.CharField(blank=True, max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='companion.companionconversation')),
            ],
            options={
                'verbose_name': 'Companion Message',
                'verbose_name_plural': 'Companion Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
