# Generated by Django 5.2.6 on 2025-09-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutus_feature_hero_partner_testimonial_whychooseus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whychooseus',
            name='icon',
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='why_image',
            field=models.ImageField(default=1, upload_to='why_images/'),
            preserve_default=False,
        ),
    ]
