# Generated by Django 5.2.6 on 2025-09-27 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_whychooseus_icon_whychooseus_why_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='featured_images/')),
                ('alt_text', models.CharField(help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('usage', models.CharField(choices=[('hero', 'Hero Section'), ('about', 'About Section'), ('services', 'Services Section'), ('features', 'Features Section'), ('testimonials', 'Testimonials Section'), ('portfolio', 'Portfolio Section'), ('blog', 'Blog Section'), ('contact', 'Contact Section'), ('footer', 'Footer Section'), ('general', 'General Use')], default='general', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when image is clicked')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Featured Image',
                'verbose_name_plural': 'Featured Images',
                'ordering': ['usage', 'order', '-created_at'],
            },
        ),
    ]
