# Generated by Django 5.2.6 on 2025-09-28 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_featuredimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='image',
        ),
    ]
