# Generated by Django 5.2.6 on 2025-09-28 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_feature_icon_remove_feature_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name (e.g., Sua Pa LMS, Sua Pa AIVI)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of product features')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, help_text='Font awesome icon class', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('demo_url', models.URLField(blank=True, help_text='Link to product demo')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
