# Generated by Django 5.2.6 on 2025-09-27 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('text', 'Text Generation'), ('image', 'Image Generation'), ('audio', 'Audio Processing'), ('video', 'Video Processing'), ('code', 'Code Generation')], max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=100)),
                ('api_endpoint', models.URLField(blank=True)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('cost_per_token', models.DecimalField(decimal_places=8, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_api_key', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('completion', 'Text Completion'), ('generation', 'Content Generation'), ('analysis', 'Content Analysis'), ('translation', 'Translation'), ('summarization', 'Summarization')], max_length=20)),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivi.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request',
                'verbose_name_plural': 'AI Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('business', 'Business'), ('creative', 'Creative'), ('technical', 'Technical'), ('educational', 'Educational'), ('personal', 'Personal')], max_length=20)),
                ('prompt_template', models.TextField()),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivi.aimodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Template',
                'verbose_name_plural': 'AI Templates',
            },
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_consumed', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aivi.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Log',
                'verbose_name_plural': 'AI Usage Logs',
                'unique_together': {('user', 'ai_model', 'date')},
            },
        ),
    ]
